- name: Install Chrome 126 + Chromedriver (Chrome for Testing way)
  run: |
    # Встановлюємо Chrome 126 for Testing
    wget -q https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/126.0.6478.126/linux64/chrome-linux64.zip
    unzip chrome-linux64.zip
    sudo mv chrome-linux64 /opt/chrome
    sudo ln -s /opt/chrome/chrome /usr/bin/google-chrome

    # Перевіряємо версію Chrome
    google-chrome --version

    # Встановлюємо Chromedriver із Chrome for Testing
    wget -q https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/126.0.6478.126/linux64/chromedriver-linux64.zip
    unzip chromedriver-linux64.zip
    sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
    sudo chmod +x /usr/local/bin/chromedriver

    # Перевірка версії Chromedriver
    chromedriver --version
