name: Microsoft Rewards Farmer

on:
  schedule:
    - cron: '0 10 * * *' # Щодня о 10:00 UTC
  workflow_dispatch:

jobs:
  farm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable unzip

    - name: Install Chromedriver
      run: |
        # Отримуємо основну версію Chrome
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+' | head -1)
        echo "Версія Chrome: $CHROME_VERSION"
        CHROME_MAJOR_VERSION=${CHROME_VERSION%%.*}
        
        # Спробуємо знайти сумісну версію Chromedriver
        DRIVER_VERSION=""
        for i in $(seq 0 2); do
          TRY_VERSION=$((CHROME_MAJOR_VERSION - i))
          RESPONSE=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${TRY_VERSION}")
          if [[ "$RESPONSE" != *"NoSuchKey"* && "$RESPONSE" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            DRIVER_VERSION=$RESPONSE
            break
          fi
        done
        
        # Якщо версію не знайдено, спробуємо наступну версію
        if [ -z "$DRIVER_VERSION" ]; then
          for i in $(seq 1 2); do
            TRY_VERSION=$((CHROME_MAJOR_VERSION + i))
            RESPONSE=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${TRY_VERSION}")
            if [[ "$RESPONSE" != *"NoSuchKey"* && "$RESPONSE" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              DRIVER_VERSION=$RESPONSE
              break
            fi
          done
        fi
        
        # Перевіряємо, чи знайдено версію
        if [ -z "$DRIVER_VERSION" ]; then
          echo "Помилка: Не вдалося знайти сумісну версію Chromedriver для Chrome $CHROME_VERSION"
          exit 1
        fi
        echo "Версія Chromedriver: $DRIVER_VERSION"
        
        # Завантажуємо та встановлюємо Chromedriver
        wget -q "https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip"
        if [ $? -ne 0 ]; then
          echo "Помилка: Не вдалося завантажити Chromedriver $DRIVER_VERSION"
          exit 1
        fi
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
        chromedriver --version

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create accounts.json
      env:
        ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}
      run: |
        if [ -z "$ACCOUNTS_JSON" ]; then
          echo "Помилка: Секрет ACCOUNTS_JSON не встановлено"
          exit 1
        fi
        echo "$ACCOUNTS_JSON" > accounts.json
        cat accounts.json # Для налагодження

    - name: Initialize farmer.log
      run: |
        echo "Ініціалізація farmer.log..." > farmer.log

    - name: Run farmer
      run: |
        python main.py 2>&1 | tee -a farmer.log
      continue-on-error: true

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: farmer-logs
        path: farmer.log
