name: Microsoft Rewards Farmer

on:
  schedule:
    - cron: '0 10 * * *' # Щодня о 10:00 UTC
  workflow_dispatch:

jobs:
  farm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create accounts.json
      env:
        ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}
      run: |
        if [ -z "$ACCOUNTS_JSON" ]; then
          echo "Помилка: Секрет ACCOUNTS_JSON не встановлено"
          exit 1
        fi
        echo "$ACCOUNTS_JSON" > accounts.json
        cat accounts.json # Для налагодження

    - name: Initialize farmer.log
      run: |
        echo "Ініціалізація farmer.log..." > farmer.log

    - name: Run farmer
      run: |
        python main.py 2>&1 | tee -a farmer.log
      continue-on-error: true

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: farmer-logs
        path: farmer.log
