name: Microsoft Rewards Farmer

on:
  schedule:
    - cron: '0 12 * * *'  # Runs daily at 12:00 UTC
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  farm-rewards:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: latest

    - name: Run Microsoft Rewards Farmer
      run: python main.py
      env:
        ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}
